apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: devops-microservices
type: Opaque
stringData:
  DATABASE_URL: postgresql://devops:devops@postgres-svc:5432/devops_db
  REDIS_URL: redis://redis-svc:6379/0
  POSTGRES_USER: devops
  POSTGRES_PASSWORD: devops
