apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-microservices

  source:
    repoURL: https://github.com/ChAbde17/devops-microservices-gitops.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-prod

  # ── SYNC POLICY: Manual for production ──
  # No 'automated' block = manual sync only (you click "Sync" in ArgoCD UI)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m